### ISSUE TITLE
It this crate deprecated?

### ISSUE THREAD

**Issue by jgsimard** [fusion-engineering/nalgebra-numpy#4]
Hi, the crate numpy now supports nalgebra in version 0.18 (https://github.com/PyO3/rust-numpy/releases/tag/v0.18.0)  as far as I can know.  Does this means that this crate is deprecated? 
thanks

**Comment by de-vri-es** [comment]
Yes, it is no longer needed :)

**Comment by jgsimard** [comment]
Thanks for the info!
